yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AuthorPage.as_view(), name='author'),
    path('tech/', views.TechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='post_group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='ad_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Сообщение',
        help_text='Текст сообщения'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Дата публикации сообщения'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор сообщения',
        help_text='Автор публиковавший сообщение'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа принадлежности сообщения'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Картинка для сообщения'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:30]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группа',
        help_text='Название группы'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='Группа',
        help_text='Уникальное название группы'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Описание группы'
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Сообщение для комментариев',
        help_text='Сообщение для комментариев'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',
        verbose_name='Автор комментария',
        help_text='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст комментария',
        null=False
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария',
        help_text='Дата публикации комментария'
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Автор комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор комментируемого сообщения'
    )

    class Meta:
        verbose_name = 'follower'
        verbose_name_plural = 'followers'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_pair'
            ),
        )

    def __str__(self):
        return f'{self.user}, {self.author}'

yatube/posts/forms.py
from django import forms

from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings as s
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from posts.forms import PostForm, CommentForm
from posts.models import Post, Group, User, Comment, Follow


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, s.NUMBER_MESSAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, s.NUMBER_MESSAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    count = post_list.count()
    paginator = Paginator(post_list, s.NUMBER_MESSAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    following = False
    if request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists():
        following = True
    context = {
        'author': author,
        'count': count,
        'following': following,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    template = 'posts/post_detail.html'
    count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('post')
    context = {
        'post': post,
        'count': count,
        'title': post,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            'posts:profile', post.author
        )

    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail',
            post_id
        )

    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Cтраница с подписками"""
    template = 'posts/follow.html'
    page_number = request.GET.get('page')
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user)
    context = {
        'page_obj': Paginator(posts, s.NUMBER_MESSAGES).get_page(page_number),
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписка на автора"""
    author = get_object_or_404(User, username=username)
    follower = request.user
    if follower == author:
        return redirect('posts:index')
    Follow.objects.get_or_create(
        author=author,
        user=follower
    )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора"""
    author = get_object_or_404(User, username=username)
    follower = request.user
    follower_list = Follow.objects.filter(author=author, user=follower)
    if not follower_list.exists():
        return redirect('posts:profile', username)
    follower_list.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{% if is_edit %}
  Сохранить запись
{% else %}
  Добавить запись
{% endif %}  
{% endblock %}
{% load user_filters %}  
{% block content %} 
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header" style="background-color: lightskyblue">      
          {% if is_edit %}
            Сохранить запись
          {% else %}
            Добавить запись
          {% endif %}             
        </div>
        <div class="card-body">
        {% if is_edit %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
        {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
        {% endif %}  
          {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3 textarea">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field|addclass:'form-control' }}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                </small>
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние обновления моих подписок{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  {% include 'includes/switcher.html' %}
  <h1>Последние обновления моих подписок</h1>
  {% for post in page_obj %}
    <div style="background-color: #FFF8DC; border:2px #FFF8DC solid #555; 
      border-radius:5px; margin:20px; padding:20px;">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li>
              <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
            </li>
            <li>
              <b>Дата публикации: {{ post.pub_date|date:"d E Y" }}</b>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
        </article>
      </div>
       <br/>
      {% if post.group %}  
        <a href="{% url 'posts:post_group' post.group.slug %}" 
          class="btn btn-primary">Все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}" 
      class="btn btn-primary">Подробная информация</a>
    </div>
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества: {{ group.title }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  {% block header %}
    <h1>{{ group.title }}</h1>
  {% endblock %}
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <div style="background-color: #FFF8DC; border:2px #FFF8DC solid #555; 
      border-radius:5px; margin:20px; padding:20px;">
      <ul>
        <li>
          <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if post.group %}  
        <br>
        <a href="{% url 'posts:post_group' post.group.slug %}" 
          class="btn btn-primary">Все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}" 
      class="btn btn-primary">Подробная информация</a>
    </div>
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 20 sidebar index page %}
<div class="container py-5">
  {% include 'includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <div style="background-color: #FFF8DC; border:2px #FFF8DC solid #555; 
      border-radius:5px; margin:20px; padding:20px;">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li>
              <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
            </li>
            <li>
              <b>Дата публикации: {{ post.pub_date|date:"d E Y" }}</b>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
        </article>
      </div>
      <br/>
      {% if post.group %}  
        <a href="{% url 'posts:post_group' post.group.slug %}" 
          class="btn btn-primary">Все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}" 
        class="btn btn-primary">Подробная информация</a>
    </div>
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Запись: {{ post }}...
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div style="background-color: #FFF8DC; border:2px #FFF8DC solid #555; 
    border-radius:5px; margin:20px; padding:20px;">
    <div class="row">
     <aside class="col-12 col-md-3"> 
        <ul class="list-group list-group-flush">
          <li>
            <b>Дата публикации: {{ post.pub_date|date:"d E Y" }}</b>
          </li>
          <li>
            {% if post.group %}    
              <b>Все записи группы:</b> <a href="{% url 'posts:post_group' post.group.slug %}">{{ post.group.title }}</a>
            {% endif %}
          </li>
          <li>
              <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
          </li>
          <li>
            <b><span>Всего постов автора: {{ post.author.posts.count }}</span></b>
          </li>
        </ul>
     </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.author == request.user %} 
        <button type="submit" class="btn btn-primary"> 
          <a href="{% url 'posts:post_edit' post.id %}" class="text-white" style="text-decoration: none">
            Редактировать пост
          </a>
        </button>
        {% endif %}
      </article>
    </div>
  </div>
</div>
{% include 'includes/add_comment.html' %} 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профиль пользователя: {{ author.get_full_name }}
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <h1>Сообщения пользователя {{ author.get_full_name }}</h1>
      {% if author != request.user %}
					<div>
            <h3>Всего сообщений: {{ author.posts.count }}</h3>
            <h6>Подписчиков: {{ author.following.count }}</h6>
            </br>
						<div>
              {% if following %}
                <a class="btn btn-outline-danger" href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
              {% else %}
                <a class="btn btn-success" href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
              {% endif %}
            </div>
          </div>
      {% else %}
        <h3>Всего моих сообщений: {{ author.posts.count }}</h3>
        <h6>Подписчиков: {{ author.following.count }}</h6>
        </br>
      {% endif %}
  {% for post in page_obj %}
    <div style="background-color: #FFF8DC; border:2px #FFF8DC solid #555; 
      border-radius:5px; margin:20px; padding:20px;">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li>
              <b>Автор:</b> <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
            </li>
            <li>
              <b>Дата публикации: {{ post.pub_date|date:"d E Y" }}</b>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
        </article>
      </div>
    </div>
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}